[package]
name = "citygml-spatial-id"
version = "0.1.0"
edition = "2024"

[dependencies]
kasane-logic ={path = "../kasane-logic"}
quick-xml = "0.39.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.8"
