[package]
name = "citygml-spatial-id"
version = "0.1.0"
edition = "2024"

[dependencies]
kasane-logic ={path = "../kasane-logic"}
quick-xml = "0.39.1"
ordered-float = { version = "5.1.0", default-features = false }
